apiVersion: 1

datasources:
  - name: TelemetryDB
    type: postgres
    url: timescaledb:5432
    database: telemetry_db
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
